### ISSUE TITLE
getCustomApiCall() is undefined?

### ISSUE THREAD

**Issue by urig** [BoyCook/TwitterJSClient#15]
First of all, thanks for writing and maintaining this library. Much appreciated.

I'm basically running the [usage example](https://github.com/BoyCook/TwitterJSClient) in a Node.js console application written in Visual Studio on Windows, using twitter-js-client v.0.0.5.

When the following call runs:

`twitter.getCustomApiCall('/mutes/users/ids.json', {}, error, success);`

I get this error:

> twitter.getCustomApiCall('/mutes/users/ids.json', {}, error, success);
>         ^
> TypeError: undefined is not a function
>     at Object.<anonymous> (d:\dev\TwitterMuter1\TwitterMuter1\app.js:29:9)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.runMain [as _onTimeout] (module.js:501:10)
>     at Timer.listOnTimeout (timers.js:110:15)

How come getCustomApiCall() is undefined?

**Comment by RakanNimer** [comment]
Hey @urig,
You're getting this error because this code is new and the latest version of the code hasn't been pushed to the npm registry yet. 
I created a pull request #16 (Bumped the version) now. When @BoyCook merges it and publishes to npm it'll work as it's supposed to.
Meanwhile you can remove your old module and run : 
```
npm install --save git+ssh://git@github.com:BoyCook/TwitterJSClient.git
```
and it should work fine.
Cheers

**Comment by urig** [comment]
Many thanks @RakanNimer! Unfortunately I get `Permission denied (publickey)` when I try your suggestion. Do I need to provide npm with my git credentials somehow?

**Comment by RakanNimer** [comment]
Hmm, could you try to clone with https instead of ssh : 
```
npm install --save git+https://git@github.com:BoyCook/TwitterJSClient.git
```

**Comment by RakanNimer** [comment]
Also read [here](https://docs.npmjs.com/files/package.json#github-urls) you can directly do this : 
``` 
npm install --save BoyCook/TwitterJSClient
```

**Comment by urig** [comment]
Thanks again @RakanNimer - This did the trick:
```
npm install --save git+https://git@github.com:BoyCook/TwitterJSClient.git
```

**Comment by RakanNimer** [comment]
No problem at all !  Will let you know once it's on npm :)

**Comment by BoyCook** [comment]
I've merged the pull request to increase the version
