### ISSUE TITLE
What the hell is happening in the README?

### ISSUE THREAD

**Issue by mvrozanti** [BoyCook/TwitterJSClient#74]
Why are credentials stored *nowhere*?
Why is indentation like that?
What where do I pass my credentials as arguments? Why can't we have nice things? This is the third api client I'm looking for Twitter and none seem to cover my use case. I had hope in this one after I was the stars only to have it quickly crushed by this nonsense README.

What is the README supposed to show?

**Comment by psnehanshu** [comment]
But then why is this library recommended by Twitter? https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries
