### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by billybonks** [BoyCook/TwitterJSClient#9]
why is this library not added to npm registery

**Comment by sunild** [comment]
Agreed! It would be nice to use a versioned package, rather than the latest code from github.

**Comment by BoyCook** [comment]
I'd like to publish but there's currently a version on npm published by @nickadmolina / @molina - this will need to be removed before I can publish.

**Comment by RakanNimer** [comment]
Publish it as twitter-node-client and change the README accordingly. Old
users will get pointed to @nickadmolina's outdated fork until he changes it
to deprecated.

**Comment by jasonhargrove** [comment]
sub, re npm out of date

**Comment by BoyCook** [comment]
This is now published to NPM at:

https://www.npmjs.com/package/twitter-node-client
